spring.profiles.active: reflect
descriptorFileName: data/proto/services.desc
xmlCallJmsDestination: blockchain-xmlcall
namespacePrefix: http://www.luxoft.com/services.xsd
xsdPath: data/proto/xsd

spring.activemq.broker-url: tcp://localhost:61616

---
spring.profiles: reflect
connectorClass: com.luxoft.xmlcall.reflect.XmlCallReflectionConnector
connectorArg: services

---
spring.profiles: fabric
connectorClass: XmlCallFabricConnector
connectorArg: config.yaml

---
spring.profiles: fabric-local
connectorClass: XmlCallFabricConnector
connectorArg: network-local/fabric-devnet.yaml
